baseURL = "localhost:1313"
languageCode = "en-us"
title = "Renan Oliveira - Big Data, Machine Learning e Data Science"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Blog pessoal do Renan Oliveira, Cofundador do Data Bootcamp e Especialista em Big Data da Globo.com"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "me@renanoliveira.net"
    twitter = "renan_oliveira"
    linkedin = "https://www.linkedin.com/in/renanmoreiradeoliveira/"
    medium = "renan_oliveira"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "foto.png"
    subtitle = "Olá! Eu sou o Renan Oliveira, carioca, especialista em Big Data e Data Science."
    hero_right = ["**Currently doing consultancy work at UX Society. Previously doing UX and product at Agoda in Bangkok, Thailand as an international intern.**", "I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.", "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.", "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).", "I'm finishing my Bachelor's degree in Management Information Systems at the Ateneo de Manila University, expecting to graduate in 2018."]
    resume = "ResumeCollado.pdf"

[params.process]
    enable = false

[params.case_studies]
    enable = true
    title = "Keynotes"
    subtitle = "principais apresentações"

[params.footer]
    enable = true
